#!/usr/bin/env bash
# Runs on the one authorized EC2 through SSM. Inputs are generated by deploy.py.
set -Eeuo pipefail
bucket=$1
release=$2
archive_sha=$3
region=$4
[[ "$bucket" =~ ^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$ ]]
[[ "$release" =~ ^[a-f0-9]{40}-[0-9]+-[0-9]+$ ]]
[[ "$archive_sha" =~ ^[a-f0-9]{64}$ ]]
[[ "$region" =~ ^[a-z]{2}-[a-z]+-[0-9]+$ ]]
base=/opt/usedcar
install -d -m 755 "$base/releases" "$base/incoming"
exec 9>"$base/deploy.lock"
flock -n 9 || { echo 'Another deployment is active' >&2; exit 1; }
target="$base/releases/$release"
previous=""
if [[ -L "$base/current" ]]; then previous=$(readlink -f "$base/current"); fi
[[ -z "$previous" || "$previous" == "$base/releases/"* ]]
[[ ! -e "$target" ]] || { echo 'Release already exists; rerun with a new attempt ID' >&2; exit 1; }
switched=0
rollback() {
    code=$?
    trap - ERR
    if [[ "$switched" == 1 ]]; then
        docker compose -f "$target/deploy/compose.yaml" --env-file "$target/deploy/.env" logs --tail=50 || true
        if [[ -n "$previous" && -f "$previous/deploy/.env" ]]; then
            echo "Restoring previous release: $previous"
            if docker compose -f "$previous/deploy/compose.yaml" --env-file "$previous/deploy/.env" up -d --no-build --wait --wait-timeout 180; then
                echo 'Rollback healthy; failed deployment remains failed.'
            else
                echo 'ROLLBACK FAILED: operator intervention required.' >&2
            fi
        else
            echo 'No previous release exists; operator intervention required.' >&2
        fi
    fi
    exit "$code"
}
trap rollback ERR

python3 - "$bucket" "$release" "$archive_sha" "$region" <<'PY'
import boto3, hashlib, json, pathlib, sys, tarfile, time
from botocore.exceptions import ClientError
bucket, release, expected, region = sys.argv[1:]
base = pathlib.Path('/opt/usedcar')
archive = base / 'incoming' / (release + '.tar')
s3 = boto3.client('s3', region_name=region)
for attempt in range(6):
    try:
        s3.download_file(bucket, 'releases/' + release + '.tar', str(archive))
        break
    except ClientError:
        if attempt == 5: raise
        time.sleep(5)
with archive.open('rb') as handle:
    if hashlib.file_digest(handle, 'sha256').hexdigest() != expected:
        raise ValueError('Release checksum mismatch')
allowed = {'images.tar.gz', 'deploy/compose.yaml', 'release.json'}
target = base / 'releases' / release
with tarfile.open(archive, 'r:') as tar:
    members = tar.getmembers()
    if len(members) != 3 or {m.name for m in members} != allowed:
        raise ValueError('Unexpected release members')
    if any(not m.isfile() or m.size > 2_000_000_000 for m in members):
        raise ValueError('Invalid release member')
    for member in members:
        path = target / member.name
        path.parent.mkdir(parents=True, exist_ok=True)
        with tar.extractfile(member) as source, path.open('wb') as out:
            import shutil
            shutil.copyfileobj(source, out)
(target / 'deploy/.env').write_text('RELEASE=' + release + '\n')
metadata = json.loads((target / 'release.json').read_text())
if metadata['release'] != release:
    raise ValueError('Release identity mismatch')
archive.unlink()
PY

docker load -i "$target/images.tar.gz"
docker compose -f "$target/deploy/compose.yaml" --env-file "$target/deploy/.env" config --quiet
switched=1
docker compose -f "$target/deploy/compose.yaml" --env-file "$target/deploy/.env" up -d --no-build --wait --wait-timeout 180

python3 - "$target/release.json" <<'PY'
import json, sys, urllib.request
metadata = json.load(open(sys.argv[1]))
with urllib.request.urlopen('http://127.0.0.1/api/health/ready', timeout=10) as response:
    ready = json.load(response)
assert ready['release'] == metadata['release'], 'Wrong application release'
assert ready['model_version'] == metadata['model_sha256'][:16], 'Wrong model version'
request = urllib.request.Request('http://127.0.0.1/api/v1/predict',
    data=json.dumps(metadata['smoke_input']).encode(), headers={'Content-Type': 'application/json'})
with urllib.request.urlopen(request, timeout=10) as response:
    result = json.load(response)
assert result['predicted_price'] == metadata['expected_price'], 'Prediction mismatch'
print(json.dumps({'release': metadata['release'], 'model': ready['model_version'], 'smoke': 'passed'}))
PY

# Promotion happens only after both containers and actual inference are verified.
[[ -z "$previous" ]] || printf '%s\n' "$previous" > "$base/previous-release"
ln -sfn "$target" "$base/current.next"
mv -Tf "$base/current.next" "$base/current"
trap - ERR
# Loaded images provide rollback; discard the redundant large transfer archive.
rm -- "$target/images.tar.gz" || echo 'Transfer archive cleanup deferred'
echo "Deployed $release"
